ee_service_account_email = "savar-no2--8-to-2025-c1f7606de@industrial-glow-461921-k4.iam.gserviceaccount.com"
ee_project_id = "industrial-glow-461921-k4"

[ee_service_account_key]
type = "service_account"
project_id = "industrial-glow-461921-k4"
private_key_id = "d5fe2b4d340250b1743fb99ccd28587d93dc6061"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCu4j2IYuS2zVc5
aCsbHTRt3gGeI6WXS277eqiAiC046OZBiTN6t9V/dmQSXCeLc/mFV1DbmaBub686
zBlPR62x0nEhF7omnpadAN4bAC5qV7MktKFJLGL2/YFxxxbXLrY7meBD/k0xzYQZ
DYM9FJ16eQrsho/91IiIKKj1AN1qgBNhJBaPjUYqkTUrM6uXiyRALIqObEHIFvJg
KOP5MJo7wFt4olxG56s2fUiCwgFOhc7BqG4Ik4uA6V8uahwD8uWYOxhCfPmYEasq
Tog9eSstxQIgboub5XWGgI8TzqBwA7kFJRP/6Mw4KgXaKJiFz376sToC7Sx+u96f
9lmJ6r1hAgMBAAECggEAA4FV9hAWK85XfQy04ld5i4MhVCurVm5oII6TYjqHcYMR
QZqMwhjSteS/e/+n/YTtMbHlGZAYNsxQd+j+eps3We6CGrR3AjKNeLqZJ/we+pNH
FuUmvTnBbWDGqA1iQ9jcq5iu7TeOM4n542aG98YTtH83uIjJhZV6YiZlrmiG7fwi
4Z1Ze4J39k/qOnPUylMy00IFWSHu+JL9ryR3P3WFQfQbgqGwmCm684aOLvq4ZbxT
FrkOxNTR+PqixHmqLgrX/KRbSyGaUZ6X4miJrtUuAMcz9uSUyZwIm/LMzXJrxwlK
TzrZdYDdv6KIaqVTXypL3zUA7AVSeZhIb3t/uVRLQwKBgQDj9w33Hsef3wA1sJXB
FeeOfKqluUeCt3ZCWdkrze8WK5LZiE7GpUbMbiFnPpSeFgEXUkXX8YlfvFmgnK+S
ERbJZobVxuPE2PQzpJzUnA+R5M7ya3V7uNNwnIiqx3DGxeQ9TxR3768/jdvSq5Fl
UrexEaOoBI696QzYOhGCj4gn9wKBgQDEZAubGWStnsnfKot1S6nRdCpeMVRouJWK
o22IaOYnsNTuVBwZ2M9KQnmml2Tt1adArgoYXnz+EQInocMDJh4ZtXd+KQZNQLUk
VIhBxoUrKvXGEnPOntKSlsMHJE/xggBnCTgYqk5J3rimwWYhRYQnz+XH/8oaRAvZ
8AL+j6JfZwKBgQCxRiniBlmOhUgQeGW8ZWBQebnqbg6iJDEen+g2HErUnsXvzAQW
jehkiTAIra280be/fwc5Smddv4ajU7VkjU1/CO/JxoTRSzV8A4LCAypIdfpIojAW
KkCizdeplraonLNEyf5M1mMdtR9A0JKcjJq0Y9c0jXbDUDvg2idLtHpZOQKBgCys
hWdWs2w7PrihOPAJsiuPPUQH/KeFtZ6/5l6tXg2RUB6Wy32lsCG4VWvr7G2duFoi
PPGmLNCulcrmJTJGLXqzqObt9h0EpzAIeqZbvlc/goD4GZfa0RO/b8XkILtTUzwd
AMG7m+t52o80V0MiSRm1VRPVv+eRqxB8ZHH7wnfpAoGADvlW/Dyf+JJFdeHHnaXX
L4RY8nXHWgWgxUdr3joBRI7dqK5ywjedyMoNg96TUk+1qWHV1x2PflPCTzFJA6Bd
HltSZRqiTMDfllHyOzxFl2EQHiNrOXANVVUjQVSr0aKFtHy5BfajFxQ/YHPqNQQm
AeUbX3u+7eX7sQQotkhUKlI=
-----END PRIVATE KEY-----
"""
client_email = "savar-no2--8-to-2025-c1f7606de@industrial-glow-461921-k4.iam.gserviceaccount.com"
client_id = "106722504808472045292"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/savar-no2--8-to-2025-c1f7606de%40industrial-glow-461921-k4.iam.gserviceaccount.com"

